services:
  web:
    build:
      dockerfile: ./packages/web-server/Dockerfile
      context: .
    ports:
      - 80:80

  back:
    build:
      dockerfile: ./packages/back-server/Dockerfile
      context: .
    ports:
      - 6666:6666