services:
  web:
    build:
      dockerfile: ./packages/web-server/Dockerfile
      context: .
    ports:
      - 80:80

  back:
    build:
      dockerfile: ./packages/back-server/Dockerfile
      context: .
    ports:
      - 666:666

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "lacolico"
      POSTGRES_PASSWORD: "1q2w3e4r!"
    volumes:
      - pgPersistence:/var/lib/postgresql
volumes:
  pgPersistence:
    external: true
